spring:
  config:
    import: "optional:file:.env[.properties]"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 실제 계정
    password: ${MAIL_PASSWORD} # 구글 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}          # 발급받은 클라이언트 ID
            client-secret: ${GOOGLE_CLIENT_SECRET}  # 발급받은 보안 비밀번호
            scope:
              - email
              - profile
  application:
    name: ceni-market-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

server:
  port: 8088

logging:
  level:
    org.hibernate.SQL: info #debug
    org.hibernate.orm.jdbc.bind: info #trace

jwt:
  # 최소 32자 이상의 임의의 문자열을 입력하세요
  secret: ${JWT_SECRET}
  # 30분 (밀리초 단위)
  access-expiration: 180000000
  # 7일
  refresh-expiration: 604800000


